/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MealPlanRouteImport } from './routes/meal-plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as AccessTokensRouteImport } from './routes/access-tokens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesUploadRouteImport } from './routes/recipes.upload'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesLibraryRouteImport } from './routes/recipes.library'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as RecipesLibraryViewRouteImport } from './routes/recipes.library_.view'
import { Route as RecipesEditIdRouteImport } from './routes/recipes.edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanRoute = MealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessTokensRoute = AccessTokensRouteImport.update({
  id: '/access-tokens',
  path: '/access-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesUploadRoute = RecipesUploadRouteImport.update({
  id: '/recipes/upload',
  path: '/recipes/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesLibraryRoute = RecipesLibraryRouteImport.update({
  id: '/recipes/library',
  path: '/recipes/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesLibraryViewRoute = RecipesLibraryViewRouteImport.update({
  id: '/recipes/library_/view',
  path: '/recipes/library/view',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesEditIdRoute = RecipesEditIdRouteImport.update({
  id: '/recipes/edit/$id',
  path: '/recipes/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-tokens': typeof AccessTokensRoute
  '/household': typeof HouseholdRoute
  '/login': typeof LoginRoute
  '/meal-plan': typeof MealPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/shopping-list': typeof ShoppingListRoute
  '/signup': typeof SignupRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/library': typeof RecipesLibraryRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/upload': typeof RecipesUploadRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/edit/$id': typeof RecipesEditIdRoute
  '/recipes/library/view': typeof RecipesLibraryViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-tokens': typeof AccessTokensRoute
  '/household': typeof HouseholdRoute
  '/login': typeof LoginRoute
  '/meal-plan': typeof MealPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/shopping-list': typeof ShoppingListRoute
  '/signup': typeof SignupRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/library': typeof RecipesLibraryRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/upload': typeof RecipesUploadRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/edit/$id': typeof RecipesEditIdRoute
  '/recipes/library/view': typeof RecipesLibraryViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-tokens': typeof AccessTokensRoute
  '/household': typeof HouseholdRoute
  '/login': typeof LoginRoute
  '/meal-plan': typeof MealPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/shopping-list': typeof ShoppingListRoute
  '/signup': typeof SignupRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/library': typeof RecipesLibraryRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/upload': typeof RecipesUploadRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/edit/$id': typeof RecipesEditIdRoute
  '/recipes/library_/view': typeof RecipesLibraryViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-tokens'
    | '/household'
    | '/login'
    | '/meal-plan'
    | '/onboarding'
    | '/pantry'
    | '/shopping-list'
    | '/signup'
    | '/recipes/$id'
    | '/recipes/library'
    | '/recipes/new'
    | '/recipes/upload'
    | '/recipes/'
    | '/recipes/edit/$id'
    | '/recipes/library/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-tokens'
    | '/household'
    | '/login'
    | '/meal-plan'
    | '/onboarding'
    | '/pantry'
    | '/shopping-list'
    | '/signup'
    | '/recipes/$id'
    | '/recipes/library'
    | '/recipes/new'
    | '/recipes/upload'
    | '/recipes'
    | '/recipes/edit/$id'
    | '/recipes/library/view'
  id:
    | '__root__'
    | '/'
    | '/access-tokens'
    | '/household'
    | '/login'
    | '/meal-plan'
    | '/onboarding'
    | '/pantry'
    | '/shopping-list'
    | '/signup'
    | '/recipes/$id'
    | '/recipes/library'
    | '/recipes/new'
    | '/recipes/upload'
    | '/recipes/'
    | '/recipes/edit/$id'
    | '/recipes/library_/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessTokensRoute: typeof AccessTokensRoute
  HouseholdRoute: typeof HouseholdRoute
  LoginRoute: typeof LoginRoute
  MealPlanRoute: typeof MealPlanRoute
  OnboardingRoute: typeof OnboardingRoute
  PantryRoute: typeof PantryRoute
  ShoppingListRoute: typeof ShoppingListRoute
  SignupRoute: typeof SignupRoute
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesLibraryRoute: typeof RecipesLibraryRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesUploadRoute: typeof RecipesUploadRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesEditIdRoute: typeof RecipesEditIdRoute
  RecipesLibraryViewRoute: typeof RecipesLibraryViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan': {
      id: '/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-tokens': {
      id: '/access-tokens'
      path: '/access-tokens'
      fullPath: '/access-tokens'
      preLoaderRoute: typeof AccessTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/upload': {
      id: '/recipes/upload'
      path: '/recipes/upload'
      fullPath: '/recipes/upload'
      preLoaderRoute: typeof RecipesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/library': {
      id: '/recipes/library'
      path: '/recipes/library'
      fullPath: '/recipes/library'
      preLoaderRoute: typeof RecipesLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/library_/view': {
      id: '/recipes/library_/view'
      path: '/recipes/library/view'
      fullPath: '/recipes/library/view'
      preLoaderRoute: typeof RecipesLibraryViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/edit/$id': {
      id: '/recipes/edit/$id'
      path: '/recipes/edit/$id'
      fullPath: '/recipes/edit/$id'
      preLoaderRoute: typeof RecipesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessTokensRoute: AccessTokensRoute,
  HouseholdRoute: HouseholdRoute,
  LoginRoute: LoginRoute,
  MealPlanRoute: MealPlanRoute,
  OnboardingRoute: OnboardingRoute,
  PantryRoute: PantryRoute,
  ShoppingListRoute: ShoppingListRoute,
  SignupRoute: SignupRoute,
  RecipesIdRoute: RecipesIdRoute,
  RecipesLibraryRoute: RecipesLibraryRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesUploadRoute: RecipesUploadRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesEditIdRoute: RecipesEditIdRoute,
  RecipesLibraryViewRoute: RecipesLibraryViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
